name: 'Artifact downloader'
description: 'download an artifact'
author: 'Bettermarks GmbH'
inputs:
  repo:
    description: 'the repository to download from'
  token:
    description: 'the personal access token'
  artifact_name:
    description: 'the name of the artifact'
  wait_seconds:
    description: 'wait for the artifact to appear'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  color: "yellow"
  icon: "download"
