name: 'Artifact downloader'
description: 'download an artifact'
author: 'Bettermarks GmbH'
inputs:
  repo:
    description: 'the repository to download from'
  token:
    description: 'the personal access token'
  artifact_name:
    description: 'the name of the artifact'
runs:
  using: 'python3'
  main: 'dist/action.py'
branding:
  color: "yellow"
  icon: "download"
