name: Integration Test
on: [push]
jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/upload-artifact@v2
        with:
          name: "${ GITHUB_SHA }"
          path: action.yml

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for artifact to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
          checkName: artifact

      - uses: actions/checkout@master

      - name: Self test
        id: selftest

        # Put your action repo here
        uses: ./
        with:
          artifact_name: "${ GITHUB_SHA }"
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"

      - name: Check outputs
        run: |
          test "${{ steps.selftest.outputs.myOutput }}" == "Artifact downloaded: ${{ env.GITHUB_SHA }}"
